version: '3.8'

services:
  dex:
    build: .
    container_name: dex-oidc
    network_mode: host
    volumes:
      - dex-data:/var/dex
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  dex-data:
